// Client-side auth state — Supabase session + user_roles (HANDOFF §6).
// Single module-level store so every consumer (route gate, login page,
// sidebar sign-out) shares one session subscription.
import { useEffect, useState } from "react";
import type { Session, SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";

export type AuthRole = "admin" | "clinician" | "patient";

export type AuthState = {
  status: "loading" | "signed-out" | "ready";
  userId: string | null;
  email: string | null;
  roles: AuthRole[];
};

// types.ts is regenerated by Lovable after the migrations run; until then the
// Database generic has no tables, so queries go through an untyped view.
const db = supabase as unknown as SupabaseClient<any, "public", any>;

let state: AuthState = { status: "loading", userId: null, email: null, roles: [] };
const listeners = new Set<() => void>();
let started = false;

function setState(next: AuthState) {
  state = next;
  listeners.forEach((fn) => fn());
}

async function loadRoles(userId: string): Promise<AuthRole[]> {
  try {
    const { data, error } = await db.from("user_roles").select("role").eq("user_id", userId);
    if (error) return [];
    return (data ?? []).map((r: { role: AuthRole }) => r.role);
  } catch {
    return [];
  }
}

async function applySession(session: Session | null) {
  if (!session?.user) {
    setState({ status: "signed-out", userId: null, email: null, roles: [] });
    return;
  }
  const roles = await loadRoles(session.user.id);
  setState({
    status: "ready",
    userId: session.user.id,
    email: session.user.email ?? null,
    roles,
  });
}

function ensureStarted() {
  if (started || typeof window === "undefined") return;
  started = true;
  (async () => {
    try {
      const { data } = await supabase.auth.getSession();
      await applySession(data.session);
      supabase.auth.onAuthStateChange((_event, session) => {
        // Defer: awaiting supabase calls inside this callback can deadlock.
        setTimeout(() => void applySession(session), 0);
      });
    } catch (err) {
      console.warn("[auth] Supabase unavailable, treating as signed out:", err);
      setState({ status: "signed-out", userId: null, email: null, roles: [] });
    }
  })();
}

export function useAuth(): AuthState {
  const [snapshot, setSnapshot] = useState(() => state);
  useEffect(() => {
    ensureStarted();
    const sync = () => setSnapshot(state);
    listeners.add(sync);
    sync();
    return () => {
      listeners.delete(sync);
    };
  }, []);
  return snapshot;
}

export function isStaff(roles: AuthRole[]): boolean {
  return roles.includes("admin") || roles.includes("clinician");
}

export async function signInWithPassword(email: string, password: string): Promise<{ error?: string }> {
  try {
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) return { error: error.message };
    return {};
  } catch (err) {
    return { error: err instanceof Error ? err.message : "Sign-in failed." };
  }
}

export async function signUpWithPassword(
  email: string,
  password: string,
  firstName?: string,
  lastName?: string,
): Promise<{ error?: string; needsConfirmation?: boolean }> {
  try {
    const { data, error } = await supabase.auth.signUp({
      email,
      password,
      options: {
        emailRedirectTo: `${window.location.origin}/portal`,
        data: { first_name: firstName || undefined, last_name: lastName || undefined },
      },
    });
    if (error) return { error: error.message };
    // When email confirmation is on, there's a user but no active session yet.
    return { needsConfirmation: !data.session };
  } catch (err) {
    return { error: err instanceof Error ? err.message : "Sign-up failed." };
  }
}

export async function signInWithGoogle(redirectTo?: string): Promise<{ error?: string }> {
  try {
    const { error } = await supabase.auth.signInWithOAuth({
      provider: "google",
      options: {
        redirectTo: `${window.location.origin}${redirectTo ?? "/portal"}`,
      },
    });
    if (error) return { error: error.message };
    return {};
  } catch (err) {
    return { error: err instanceof Error ? err.message : "Sign-in failed." };
  }
}

export async function requestPasswordReset(email: string): Promise<{ error?: string }> {
  try {
    const { error } = await supabase.auth.resetPasswordForEmail(email, {
      redirectTo: `${window.location.origin}/admin/login`,
    });
    if (error) return { error: error.message };
    return {};
  } catch (err) {
    return { error: err instanceof Error ? err.message : "Reset request failed." };
  }
}

export async function signOut(): Promise<void> {
  try {
    await supabase.auth.signOut();
  } catch {
    /* already signed out */
  }
}
