/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelehealthRouteImport } from './routes/telehealth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PatientResourcesRouteImport } from './routes/patient-resources'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DrChenRouteImport } from './routes/dr-chen'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as PhysiciansIndexRouteImport } from './routes/physicians.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as ConditionsIndexRouteImport } from './routes/conditions.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as PhysiciansSlugRouteImport } from './routes/physicians.$slug'
import { Route as PatientProgramsRouteImport } from './routes/patient.programs'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientNotificationsRouteImport } from './routes/patient.notifications'
import { Route as PatientMessagesRouteImport } from './routes/patient.messages'
import { Route as PatientMedicationsRouteImport } from './routes/patient.medications'
import { Route as PatientHelpRouteImport } from './routes/patient.help'
import { Route as PatientFormsRouteImport } from './routes/patient.forms'
import { Route as PatientEducationRouteImport } from './routes/patient.education'
import { Route as PatientDocumentsRouteImport } from './routes/patient.documents'
import { Route as PatientCarePlanRouteImport } from './routes/patient.care-plan'
import { Route as PatientBillingRouteImport } from './routes/patient.billing'
import { Route as LocationsStateRouteImport } from './routes/locations.$state'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ConditionsSlugRouteImport } from './routes/conditions.$slug'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRecordsRouteImport } from './routes/admin.records'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLabsRouteImport } from './routes/admin.labs'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminClinicalRouteImport } from './routes/admin.clinical'
import { Route as AdminCarePlansRouteImport } from './routes/admin.care-plans'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as PatientTelehealthIndexRouteImport } from './routes/patient.telehealth.index'
import { Route as PatientLabsIndexRouteImport } from './routes/patient.labs.index'
import { Route as PatientHealthIndexRouteImport } from './routes/patient.health.index'
import { Route as PatientAppointmentsIndexRouteImport } from './routes/patient.appointments.index'
import { Route as AdminResearchIndexRouteImport } from './routes/admin.research.index'
import { Route as AdminPatientsIndexRouteImport } from './routes/admin.patients.index'
import { Route as AdminAppointmentsIndexRouteImport } from './routes/admin.appointments.index'
import { Route as PatientTelehealthWaitingRoomRouteImport } from './routes/patient.telehealth.waiting-room'
import { Route as PatientLabsIdRouteImport } from './routes/patient.labs.$id'
import { Route as PatientHealthVitalsRouteImport } from './routes/patient.health.vitals'
import { Route as PatientAppointmentsIdRouteImport } from './routes/patient.appointments.$id'
import { Route as AdminResearchIdRouteImport } from './routes/admin.research.$id'
import { Route as AdminPatientsNewRouteImport } from './routes/admin.patients.new'
import { Route as AdminPatientsIdRouteImport } from './routes/admin.patients.$id'
import { Route as AdminAppointmentsNewRouteImport } from './routes/admin.appointments.new'
import { Route as AdminAppointmentsIdRouteImport } from './routes/admin.appointments.$id'

const TelehealthRoute = TelehealthRouteImport.update({
  id: '/telehealth',
  path: '/telehealth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientResourcesRoute = PatientResourcesRouteImport.update({
  id: '/patient-resources',
  path: '/patient-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DrChenRoute = DrChenRouteImport.update({
  id: '/dr-chen',
  path: '/dr-chen',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysiciansIndexRoute = PhysiciansIndexRouteImport.update({
  id: '/physicians/',
  path: '/physicians/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsIndexRoute = ConditionsIndexRouteImport.update({
  id: '/conditions/',
  path: '/conditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysiciansSlugRoute = PhysiciansSlugRouteImport.update({
  id: '/physicians/$slug',
  path: '/physicians/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProgramsRoute = PatientProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMessagesRoute = PatientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicationsRoute = PatientMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHelpRoute = PatientHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PatientRoute,
} as any)
const PatientFormsRoute = PatientFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => PatientRoute,
} as any)
const PatientEducationRoute = PatientEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDocumentsRoute = PatientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCarePlanRoute = PatientCarePlanRouteImport.update({
  id: '/care-plan',
  path: '/care-plan',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBillingRoute = PatientBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PatientRoute,
} as any)
const LocationsStateRoute = LocationsStateRouteImport.update({
  id: '/locations/$state',
  path: '/locations/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/conditions/$slug',
  path: '/conditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLabsRoute = AdminLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicalRoute = AdminClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarePlansRoute = AdminCarePlansRouteImport.update({
  id: '/care-plans',
  path: '/care-plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PatientTelehealthIndexRoute = PatientTelehealthIndexRouteImport.update({
  id: '/telehealth/',
  path: '/telehealth/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientLabsIndexRoute = PatientLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHealthIndexRoute = PatientHealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsIndexRoute =
  PatientAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => PatientRoute,
  } as any)
const AdminResearchIndexRoute = AdminResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsIndexRoute = AdminPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsIndexRoute = AdminAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AdminRoute,
} as any)
const PatientTelehealthWaitingRoomRoute =
  PatientTelehealthWaitingRoomRouteImport.update({
    id: '/telehealth/waiting-room',
    path: '/telehealth/waiting-room',
    getParentRoute: () => PatientRoute,
  } as any)
const PatientLabsIdRoute = PatientLabsIdRouteImport.update({
  id: '/labs/$id',
  path: '/labs/$id',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHealthVitalsRoute = PatientHealthVitalsRouteImport.update({
  id: '/health/vitals',
  path: '/health/vitals',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsIdRoute = PatientAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => PatientRoute,
} as any)
const AdminResearchIdRoute = AdminResearchIdRouteImport.update({
  id: '/research/$id',
  path: '/research/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsNewRoute = AdminPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsNewRoute = AdminAppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsIdRoute = AdminAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dr-chen': typeof DrChenRoute
  '/faq': typeof FaqRoute
  '/innovation': typeof InnovationRoute
  '/medications': typeof MedicationsRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient-resources': typeof PatientResourcesRoute
  '/portal': typeof PortalRoute
  '/telehealth': typeof TelehealthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/care-plans': typeof AdminCarePlansRoute
  '/admin/clinical': typeof AdminClinicalRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/locations/$state': typeof LocationsStateRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/care-plan': typeof PatientCarePlanRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/education': typeof PatientEducationRoute
  '/patient/forms': typeof PatientFormsRoute
  '/patient/help': typeof PatientHelpRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/programs': typeof PatientProgramsRoute
  '/physicians/$slug': typeof PhysiciansSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/physicians/': typeof PhysiciansIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/appointments/new': typeof AdminAppointmentsNewRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/new': typeof AdminPatientsNewRoute
  '/admin/research/$id': typeof AdminResearchIdRoute
  '/patient/appointments/$id': typeof PatientAppointmentsIdRoute
  '/patient/health/vitals': typeof PatientHealthVitalsRoute
  '/patient/labs/$id': typeof PatientLabsIdRoute
  '/patient/telehealth/waiting-room': typeof PatientTelehealthWaitingRoomRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/research/': typeof AdminResearchIndexRoute
  '/patient/appointments/': typeof PatientAppointmentsIndexRoute
  '/patient/health/': typeof PatientHealthIndexRoute
  '/patient/labs/': typeof PatientLabsIndexRoute
  '/patient/telehealth/': typeof PatientTelehealthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dr-chen': typeof DrChenRoute
  '/faq': typeof FaqRoute
  '/innovation': typeof InnovationRoute
  '/medications': typeof MedicationsRoute
  '/patient-resources': typeof PatientResourcesRoute
  '/portal': typeof PortalRoute
  '/telehealth': typeof TelehealthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/care-plans': typeof AdminCarePlansRoute
  '/admin/clinical': typeof AdminClinicalRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/locations/$state': typeof LocationsStateRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/care-plan': typeof PatientCarePlanRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/education': typeof PatientEducationRoute
  '/patient/forms': typeof PatientFormsRoute
  '/patient/help': typeof PatientHelpRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/programs': typeof PatientProgramsRoute
  '/physicians/$slug': typeof PhysiciansSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/conditions': typeof ConditionsIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/patient': typeof PatientIndexRoute
  '/physicians': typeof PhysiciansIndexRoute
  '/research': typeof ResearchIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/appointments/new': typeof AdminAppointmentsNewRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/new': typeof AdminPatientsNewRoute
  '/admin/research/$id': typeof AdminResearchIdRoute
  '/patient/appointments/$id': typeof PatientAppointmentsIdRoute
  '/patient/health/vitals': typeof PatientHealthVitalsRoute
  '/patient/labs/$id': typeof PatientLabsIdRoute
  '/patient/telehealth/waiting-room': typeof PatientTelehealthWaitingRoomRoute
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/patients': typeof AdminPatientsIndexRoute
  '/admin/research': typeof AdminResearchIndexRoute
  '/patient/appointments': typeof PatientAppointmentsIndexRoute
  '/patient/health': typeof PatientHealthIndexRoute
  '/patient/labs': typeof PatientLabsIndexRoute
  '/patient/telehealth': typeof PatientTelehealthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dr-chen': typeof DrChenRoute
  '/faq': typeof FaqRoute
  '/innovation': typeof InnovationRoute
  '/medications': typeof MedicationsRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient-resources': typeof PatientResourcesRoute
  '/portal': typeof PortalRoute
  '/telehealth': typeof TelehealthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/care-plans': typeof AdminCarePlansRoute
  '/admin/clinical': typeof AdminClinicalRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/locations/$state': typeof LocationsStateRoute
  '/patient/billing': typeof PatientBillingRoute
  '/patient/care-plan': typeof PatientCarePlanRoute
  '/patient/documents': typeof PatientDocumentsRoute
  '/patient/education': typeof PatientEducationRoute
  '/patient/forms': typeof PatientFormsRoute
  '/patient/help': typeof PatientHelpRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/programs': typeof PatientProgramsRoute
  '/physicians/$slug': typeof PhysiciansSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/physicians/': typeof PhysiciansIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/appointments/new': typeof AdminAppointmentsNewRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/new': typeof AdminPatientsNewRoute
  '/admin/research/$id': typeof AdminResearchIdRoute
  '/patient/appointments/$id': typeof PatientAppointmentsIdRoute
  '/patient/health/vitals': typeof PatientHealthVitalsRoute
  '/patient/labs/$id': typeof PatientLabsIdRoute
  '/patient/telehealth/waiting-room': typeof PatientTelehealthWaitingRoomRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/research/': typeof AdminResearchIndexRoute
  '/patient/appointments/': typeof PatientAppointmentsIndexRoute
  '/patient/health/': typeof PatientHealthIndexRoute
  '/patient/labs/': typeof PatientLabsIndexRoute
  '/patient/telehealth/': typeof PatientTelehealthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/dr-chen'
    | '/faq'
    | '/innovation'
    | '/medications'
    | '/patient'
    | '/patient-resources'
    | '/portal'
    | '/telehealth'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/calendar'
    | '/admin/care-plans'
    | '/admin/clinical'
    | '/admin/comments'
    | '/admin/crm'
    | '/admin/documents'
    | '/admin/insights'
    | '/admin/labs'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/records'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/website'
    | '/conditions/$slug'
    | '/insights/$slug'
    | '/legal/$slug'
    | '/locations/$state'
    | '/patient/billing'
    | '/patient/care-plan'
    | '/patient/documents'
    | '/patient/education'
    | '/patient/forms'
    | '/patient/help'
    | '/patient/medications'
    | '/patient/messages'
    | '/patient/notifications'
    | '/patient/profile'
    | '/patient/programs'
    | '/physicians/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/conditions/'
    | '/insights/'
    | '/patient/'
    | '/physicians/'
    | '/research/'
    | '/services/'
    | '/admin/appointments/$id'
    | '/admin/appointments/new'
    | '/admin/patients/$id'
    | '/admin/patients/new'
    | '/admin/research/$id'
    | '/patient/appointments/$id'
    | '/patient/health/vitals'
    | '/patient/labs/$id'
    | '/patient/telehealth/waiting-room'
    | '/admin/appointments/'
    | '/admin/patients/'
    | '/admin/research/'
    | '/patient/appointments/'
    | '/patient/health/'
    | '/patient/labs/'
    | '/patient/telehealth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/dr-chen'
    | '/faq'
    | '/innovation'
    | '/medications'
    | '/patient-resources'
    | '/portal'
    | '/telehealth'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/calendar'
    | '/admin/care-plans'
    | '/admin/clinical'
    | '/admin/comments'
    | '/admin/crm'
    | '/admin/documents'
    | '/admin/insights'
    | '/admin/labs'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/records'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/website'
    | '/conditions/$slug'
    | '/insights/$slug'
    | '/legal/$slug'
    | '/locations/$state'
    | '/patient/billing'
    | '/patient/care-plan'
    | '/patient/documents'
    | '/patient/education'
    | '/patient/forms'
    | '/patient/help'
    | '/patient/medications'
    | '/patient/messages'
    | '/patient/notifications'
    | '/patient/profile'
    | '/patient/programs'
    | '/physicians/$slug'
    | '/services/$slug'
    | '/admin'
    | '/conditions'
    | '/insights'
    | '/patient'
    | '/physicians'
    | '/research'
    | '/services'
    | '/admin/appointments/$id'
    | '/admin/appointments/new'
    | '/admin/patients/$id'
    | '/admin/patients/new'
    | '/admin/research/$id'
    | '/patient/appointments/$id'
    | '/patient/health/vitals'
    | '/patient/labs/$id'
    | '/patient/telehealth/waiting-room'
    | '/admin/appointments'
    | '/admin/patients'
    | '/admin/research'
    | '/patient/appointments'
    | '/patient/health'
    | '/patient/labs'
    | '/patient/telehealth'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/dr-chen'
    | '/faq'
    | '/innovation'
    | '/medications'
    | '/patient'
    | '/patient-resources'
    | '/portal'
    | '/telehealth'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/calendar'
    | '/admin/care-plans'
    | '/admin/clinical'
    | '/admin/comments'
    | '/admin/crm'
    | '/admin/documents'
    | '/admin/insights'
    | '/admin/labs'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/records'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/website'
    | '/conditions/$slug'
    | '/insights/$slug'
    | '/legal/$slug'
    | '/locations/$state'
    | '/patient/billing'
    | '/patient/care-plan'
    | '/patient/documents'
    | '/patient/education'
    | '/patient/forms'
    | '/patient/help'
    | '/patient/medications'
    | '/patient/messages'
    | '/patient/notifications'
    | '/patient/profile'
    | '/patient/programs'
    | '/physicians/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/conditions/'
    | '/insights/'
    | '/patient/'
    | '/physicians/'
    | '/research/'
    | '/services/'
    | '/admin/appointments/$id'
    | '/admin/appointments/new'
    | '/admin/patients/$id'
    | '/admin/patients/new'
    | '/admin/research/$id'
    | '/patient/appointments/$id'
    | '/patient/health/vitals'
    | '/patient/labs/$id'
    | '/patient/telehealth/waiting-room'
    | '/admin/appointments/'
    | '/admin/patients/'
    | '/admin/research/'
    | '/patient/appointments/'
    | '/patient/health/'
    | '/patient/labs/'
    | '/patient/telehealth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DrChenRoute: typeof DrChenRoute
  FaqRoute: typeof FaqRoute
  InnovationRoute: typeof InnovationRoute
  MedicationsRoute: typeof MedicationsRoute
  PatientRoute: typeof PatientRouteWithChildren
  PatientResourcesRoute: typeof PatientResourcesRoute
  PortalRoute: typeof PortalRoute
  TelehealthRoute: typeof TelehealthRoute
  ConditionsSlugRoute: typeof ConditionsSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  LocationsStateRoute: typeof LocationsStateRoute
  PhysiciansSlugRoute: typeof PhysiciansSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ConditionsIndexRoute: typeof ConditionsIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  PhysiciansIndexRoute: typeof PhysiciansIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telehealth': {
      id: '/telehealth'
      path: '/telehealth'
      fullPath: '/telehealth'
      preLoaderRoute: typeof TelehealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-resources': {
      id: '/patient-resources'
      path: '/patient-resources'
      fullPath: '/patient-resources'
      preLoaderRoute: typeof PatientResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation': {
      id: '/innovation'
      path: '/innovation'
      fullPath: '/innovation'
      preLoaderRoute: typeof InnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dr-chen': {
      id: '/dr-chen'
      path: '/dr-chen'
      fullPath: '/dr-chen'
      preLoaderRoute: typeof DrChenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physicians/': {
      id: '/physicians/'
      path: '/physicians'
      fullPath: '/physicians/'
      preLoaderRoute: typeof PhysiciansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/': {
      id: '/conditions/'
      path: '/conditions'
      fullPath: '/conditions/'
      preLoaderRoute: typeof ConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physicians/$slug': {
      id: '/physicians/$slug'
      path: '/physicians/$slug'
      fullPath: '/physicians/$slug'
      preLoaderRoute: typeof PhysiciansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/programs': {
      id: '/patient/programs'
      path: '/programs'
      fullPath: '/patient/programs'
      preLoaderRoute: typeof PatientProgramsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/messages': {
      id: '/patient/messages'
      path: '/messages'
      fullPath: '/patient/messages'
      preLoaderRoute: typeof PatientMessagesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medications': {
      id: '/patient/medications'
      path: '/medications'
      fullPath: '/patient/medications'
      preLoaderRoute: typeof PatientMedicationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/help': {
      id: '/patient/help'
      path: '/help'
      fullPath: '/patient/help'
      preLoaderRoute: typeof PatientHelpRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/forms': {
      id: '/patient/forms'
      path: '/forms'
      fullPath: '/patient/forms'
      preLoaderRoute: typeof PatientFormsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/education': {
      id: '/patient/education'
      path: '/education'
      fullPath: '/patient/education'
      preLoaderRoute: typeof PatientEducationRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/documents': {
      id: '/patient/documents'
      path: '/documents'
      fullPath: '/patient/documents'
      preLoaderRoute: typeof PatientDocumentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/care-plan': {
      id: '/patient/care-plan'
      path: '/care-plan'
      fullPath: '/patient/care-plan'
      preLoaderRoute: typeof PatientCarePlanRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/billing': {
      id: '/patient/billing'
      path: '/billing'
      fullPath: '/patient/billing'
      preLoaderRoute: typeof PatientBillingRouteImport
      parentRoute: typeof PatientRoute
    }
    '/locations/$state': {
      id: '/locations/$state'
      path: '/locations/$state'
      fullPath: '/locations/$state'
      preLoaderRoute: typeof LocationsStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/conditions/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/labs': {
      id: '/admin/labs'
      path: '/labs'
      fullPath: '/admin/labs'
      preLoaderRoute: typeof AdminLabsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinical': {
      id: '/admin/clinical'
      path: '/clinical'
      fullPath: '/admin/clinical'
      preLoaderRoute: typeof AdminClinicalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/care-plans': {
      id: '/admin/care-plans'
      path: '/care-plans'
      fullPath: '/admin/care-plans'
      preLoaderRoute: typeof AdminCarePlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/telehealth/': {
      id: '/patient/telehealth/'
      path: '/telehealth'
      fullPath: '/patient/telehealth/'
      preLoaderRoute: typeof PatientTelehealthIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/labs/': {
      id: '/patient/labs/'
      path: '/labs'
      fullPath: '/patient/labs/'
      preLoaderRoute: typeof PatientLabsIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/health/': {
      id: '/patient/health/'
      path: '/health'
      fullPath: '/patient/health/'
      preLoaderRoute: typeof PatientHealthIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments/': {
      id: '/patient/appointments/'
      path: '/appointments'
      fullPath: '/patient/appointments/'
      preLoaderRoute: typeof PatientAppointmentsIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/admin/research/': {
      id: '/admin/research/'
      path: '/research'
      fullPath: '/admin/research/'
      preLoaderRoute: typeof AdminResearchIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/': {
      id: '/admin/patients/'
      path: '/patients'
      fullPath: '/admin/patients/'
      preLoaderRoute: typeof AdminPatientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments/': {
      id: '/admin/appointments/'
      path: '/appointments'
      fullPath: '/admin/appointments/'
      preLoaderRoute: typeof AdminAppointmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/telehealth/waiting-room': {
      id: '/patient/telehealth/waiting-room'
      path: '/telehealth/waiting-room'
      fullPath: '/patient/telehealth/waiting-room'
      preLoaderRoute: typeof PatientTelehealthWaitingRoomRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/labs/$id': {
      id: '/patient/labs/$id'
      path: '/labs/$id'
      fullPath: '/patient/labs/$id'
      preLoaderRoute: typeof PatientLabsIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/health/vitals': {
      id: '/patient/health/vitals'
      path: '/health/vitals'
      fullPath: '/patient/health/vitals'
      preLoaderRoute: typeof PatientHealthVitalsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments/$id': {
      id: '/patient/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/patient/appointments/$id'
      preLoaderRoute: typeof PatientAppointmentsIdRouteImport
      parentRoute: typeof PatientRoute
    }
    '/admin/research/$id': {
      id: '/admin/research/$id'
      path: '/research/$id'
      fullPath: '/admin/research/$id'
      preLoaderRoute: typeof AdminResearchIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/new': {
      id: '/admin/patients/new'
      path: '/patients/new'
      fullPath: '/admin/patients/new'
      preLoaderRoute: typeof AdminPatientsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/patients/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments/new': {
      id: '/admin/appointments/new'
      path: '/appointments/new'
      fullPath: '/admin/appointments/new'
      preLoaderRoute: typeof AdminAppointmentsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments/$id': {
      id: '/admin/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/admin/appointments/$id'
      preLoaderRoute: typeof AdminAppointmentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCarePlansRoute: typeof AdminCarePlansRoute
  AdminClinicalRoute: typeof AdminClinicalRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminLabsRoute: typeof AdminLabsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminWebsiteRoute: typeof AdminWebsiteRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAppointmentsIdRoute: typeof AdminAppointmentsIdRoute
  AdminAppointmentsNewRoute: typeof AdminAppointmentsNewRoute
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
  AdminPatientsNewRoute: typeof AdminPatientsNewRoute
  AdminResearchIdRoute: typeof AdminResearchIdRoute
  AdminAppointmentsIndexRoute: typeof AdminAppointmentsIndexRoute
  AdminPatientsIndexRoute: typeof AdminPatientsIndexRoute
  AdminResearchIndexRoute: typeof AdminResearchIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCarePlansRoute: AdminCarePlansRoute,
  AdminClinicalRoute: AdminClinicalRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminLabsRoute: AdminLabsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminWebsiteRoute: AdminWebsiteRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAppointmentsIdRoute: AdminAppointmentsIdRoute,
  AdminAppointmentsNewRoute: AdminAppointmentsNewRoute,
  AdminPatientsIdRoute: AdminPatientsIdRoute,
  AdminPatientsNewRoute: AdminPatientsNewRoute,
  AdminResearchIdRoute: AdminResearchIdRoute,
  AdminAppointmentsIndexRoute: AdminAppointmentsIndexRoute,
  AdminPatientsIndexRoute: AdminPatientsIndexRoute,
  AdminResearchIndexRoute: AdminResearchIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PatientRouteChildren {
  PatientBillingRoute: typeof PatientBillingRoute
  PatientCarePlanRoute: typeof PatientCarePlanRoute
  PatientDocumentsRoute: typeof PatientDocumentsRoute
  PatientEducationRoute: typeof PatientEducationRoute
  PatientFormsRoute: typeof PatientFormsRoute
  PatientHelpRoute: typeof PatientHelpRoute
  PatientMedicationsRoute: typeof PatientMedicationsRoute
  PatientMessagesRoute: typeof PatientMessagesRoute
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientProgramsRoute: typeof PatientProgramsRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientAppointmentsIdRoute: typeof PatientAppointmentsIdRoute
  PatientHealthVitalsRoute: typeof PatientHealthVitalsRoute
  PatientLabsIdRoute: typeof PatientLabsIdRoute
  PatientTelehealthWaitingRoomRoute: typeof PatientTelehealthWaitingRoomRoute
  PatientAppointmentsIndexRoute: typeof PatientAppointmentsIndexRoute
  PatientHealthIndexRoute: typeof PatientHealthIndexRoute
  PatientLabsIndexRoute: typeof PatientLabsIndexRoute
  PatientTelehealthIndexRoute: typeof PatientTelehealthIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientBillingRoute: PatientBillingRoute,
  PatientCarePlanRoute: PatientCarePlanRoute,
  PatientDocumentsRoute: PatientDocumentsRoute,
  PatientEducationRoute: PatientEducationRoute,
  PatientFormsRoute: PatientFormsRoute,
  PatientHelpRoute: PatientHelpRoute,
  PatientMedicationsRoute: PatientMedicationsRoute,
  PatientMessagesRoute: PatientMessagesRoute,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientProgramsRoute: PatientProgramsRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientAppointmentsIdRoute: PatientAppointmentsIdRoute,
  PatientHealthVitalsRoute: PatientHealthVitalsRoute,
  PatientLabsIdRoute: PatientLabsIdRoute,
  PatientTelehealthWaitingRoomRoute: PatientTelehealthWaitingRoomRoute,
  PatientAppointmentsIndexRoute: PatientAppointmentsIndexRoute,
  PatientHealthIndexRoute: PatientHealthIndexRoute,
  PatientLabsIndexRoute: PatientLabsIndexRoute,
  PatientTelehealthIndexRoute: PatientTelehealthIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DrChenRoute: DrChenRoute,
  FaqRoute: FaqRoute,
  InnovationRoute: InnovationRoute,
  MedicationsRoute: MedicationsRoute,
  PatientRoute: PatientRouteWithChildren,
  PatientResourcesRoute: PatientResourcesRoute,
  PortalRoute: PortalRoute,
  TelehealthRoute: TelehealthRoute,
  ConditionsSlugRoute: ConditionsSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  LocationsStateRoute: LocationsStateRoute,
  PhysiciansSlugRoute: PhysiciansSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ConditionsIndexRoute: ConditionsIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  PhysiciansIndexRoute: PhysiciansIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
